[workspace]
name = "duck_engine"
version = "0.1.0"
#authors = ["Sechi <mrsechi@protonmail.com>", "Vrikka <vrikkadev@gmail.com>"]
edition = "2021"

members = ["Duck-Core", "Duck-Scene", "engine_tester"]

